name: redcard
version: '0.2.2.0'
synopsis: Applicative Validation for JSON & XML
category: Data
author: Flipstone Technology Partners
maintainer: development@flipstone.com
license: AllRightsReserved
tested-with: GHC == 7.10.3, GHC == 8.6.5
default-extensions:
- OverloadedStrings
ghc-options:
- -Wall
- -Werror
- -fno-warn-orphans
dependencies:
- base >=4.8 && <4.13
- aeson
- aeson-pretty
- bytestring
- containers
- convertible
- mtl
- scientific
- text
- transformers
- unordered-containers
- vector
- xml-conduit
library:
  source-dirs: src
  exposed-modules:
  - Data.Validation
  - Data.Validation.Aeson
  - Data.Validation.Primitives
  - Data.Validation.Types
  - Data.Validation.Types.Pure
  - Data.Validation.Types.Trans
  - Data.Validation.XML
