name: redcard
version: '0.4.0.1'
synopsis: Applicative Validation for JSON & XML
category: Data
author: Flipstone Technology Partners
maintainer: development@flipstone.com
license: AllRightsReserved
default-extensions:
- OverloadedStrings
ghc-options:
- -Wall
- -Werror
- -Wcpp-undef
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-orphans
dependencies:
- base >=4.8
- aeson
- aeson-pretty
- bytestring
- containers
- convertible
- mtl
- scientific
- text
- transformers
- unordered-containers
- vector
- xml-conduit
library:
  source-dirs: src
  exposed-modules:
  - Data.Validation
  - Data.Validation.Aeson
  - Data.Validation.Primitives
  - Data.Validation.Types
  - Data.Validation.Types.Pure
  - Data.Validation.Types.Trans
  - Data.Validation.XML
tests:
  redcard-test:
    source-dirs: test
    main: Main
    dependencies: redcard
