name: Redcard CI

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        env:
          cache-version: v1
        with:
          key: ${{ env.cache-version }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ env.cache-version }}-
          path: |
            ./stack-root

      - name: Build
        run: |
          set -e
          mkdir -p ./stack-root
          mv compose.override.github.yml compose.override.yml
          echo "PROJECT_DIR=$PWD" >> .env
          ./scripts/build
