name: Redcard CI

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Github Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-version: v1
        with:
          key: ${{ env.cache-version }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ env.cache-version }}-
          path: |
            ./stack-root

      - name: Build
        run: |
          set -e
          mkdir -p ./stack-root
          mv docker-compose.override.github.yml docker-compose.override.yml
          echo "PROJECT_DIR=$PWD" >> .env
          ./scripts/build
